# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-04 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('cover', models.ImageField(blank=True, default='default.png', upload_to='cover/django/')),
                ('content', models.TextField(blank=True)),
                ('title1', models.CharField(blank=True, max_length=255)),
                ('content1', models.TextField(blank=True)),
                ('title2', models.CharField(blank=True, max_length=255)),
                ('content2', models.TextField(blank=True)),
                ('title3', models.CharField(blank=True, max_length=255)),
                ('content3', models.TextField(blank=True)),
                ('category', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('publish', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, editable=False)),
            ],
        ),
    ]
