# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-04 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='cover',
            field=models.ImageField(blank=True, default='default.png', upload_to='cover/blog/'),
        ),
    ]
