# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-03 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrapcontent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='cover',
            field=models.ImageField(blank=True, default='default.png', upload_to='cover/bootstrap/'),
        ),
        migrations.AlterField(
            model_name='content',
            name='image1',
            field=models.ImageField(blank=True, default='default.png', upload_to='image/bootstrap/'),
        ),
        migrations.AlterField(
            model_name='content',
            name='image2',
            field=models.ImageField(blank=True, default='default.png', upload_to='image/bootstrap/'),
        ),
    ]
