# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-03 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oopcontent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='code2',
        ),
        migrations.RemoveField(
            model_name='content',
            name='text2',
        ),
        migrations.AddField(
            model_name='content',
            name='code5',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='content',
            name='content5',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='content',
            name='text5',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='content',
            name='title5',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
