# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-03 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oopcontent', '0002_auto_20200703_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='caption5',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='content',
            name='code6',
            field=models.TextField(blank=True),
        ),
    ]
