# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-30 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(blank=True, max_length=255)),
                ('subtitle1', models.CharField(blank=True, max_length=255)),
                ('cover', models.ImageField(blank=True, default='default.png', upload_to='cover/css/')),
                ('text1', models.TextField(blank=True)),
                ('image1', models.ImageField(blank=True, default='default.png', upload_to='image/css/')),
                ('capotion1', models.TextField(blank=True)),
                ('title2', models.CharField(blank=True, max_length=255)),
                ('text2', models.TextField(blank=True)),
                ('kode2', models.TextField(blank=True)),
                ('text', models.TextField(blank=True)),
                ('image2', models.ImageField(blank=True, default='default.png', upload_to='image/css/')),
                ('caption2', models.TextField(blank=True)),
                ('title3', models.CharField(blank=True, max_length=255)),
                ('kode3', models.TextField(blank=True)),
                ('text3', models.TextField(blank=True)),
                ('image3', models.ImageField(blank=True, default='default.png', upload_to='image/css/')),
                ('caption3', models.TextField(blank=True)),
                ('title4', models.CharField(blank=True, max_length=255)),
                ('kode4', models.TextField(blank=True)),
                ('text4', models.TextField(blank=True)),
                ('image4', models.ImageField(blank=True, default='default.png', upload_to='image/css/')),
                ('caption4', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('html', 'html'), ('css', 'css'), ('js', 'js'), ('dom', 'dom'), ('bootstrap', 'bootstrap'), ('python', 'python'), ('oop', 'oop'), ('django', 'django')], max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('publish', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, editable=False)),
            ],
        ),
    ]
