# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-30 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csscontent', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='capotion1',
            new_name='caption',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='kode2',
            new_name='code1',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='kode3',
            new_name='code2',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='kode4',
            new_name='code3',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='caption4',
            new_name='content3',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='subtitle1',
            new_name='subtitle',
        ),
        migrations.RemoveField(
            model_name='content',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='content',
            name='text',
        ),
        migrations.RemoveField(
            model_name='content',
            name='text4',
        ),
        migrations.RemoveField(
            model_name='content',
            name='title4',
        ),
        migrations.AddField(
            model_name='content',
            name='caption1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='content',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='content',
            name='content1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='content',
            name='content2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='content',
            name='image',
            field=models.ImageField(blank=True, default='default.png', upload_to='image/css/'),
        ),
        migrations.AddField(
            model_name='content',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
