# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-03 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('cover', models.ImageField(blank=True, default='default.png', upload_to='cover/django/')),
                ('content', models.TextField(blank=True)),
                ('title1', models.CharField(blank=True, max_length=255)),
                ('content1', models.TextField(blank=True)),
                ('code1', models.TextField(blank=True)),
                ('text1', models.TextField(blank=True)),
                ('title2', models.CharField(blank=True, max_length=255)),
                ('content2', models.TextField(blank=True)),
                ('code2', models.TextField(blank=True)),
                ('text2', models.TextField(blank=True)),
                ('image2', models.ImageField(blank=True, default='default.png', upload_to='image/django/')),
                ('caption2', models.TextField(blank=True)),
                ('title3', models.CharField(blank=True, max_length=255)),
                ('content3', models.TextField(blank=True)),
                ('code3', models.TextField(blank=True)),
                ('text3', models.TextField(blank=True)),
                ('title4', models.CharField(blank=True, max_length=255)),
                ('content4', models.TextField(blank=True)),
                ('code4', models.TextField(blank=True)),
                ('text4', models.TextField(blank=True)),
                ('title5', models.CharField(blank=True, max_length=255)),
                ('content5', models.TextField(blank=True)),
                ('code5', models.TextField(blank=True)),
                ('text5', models.TextField(blank=True)),
                ('image5', models.ImageField(blank=True, default='default.png', upload_to='image/django/')),
                ('caption5', models.TextField(blank=True)),
                ('linkA', models.CharField(blank=True, max_length=255)),
                ('linkB', models.CharField(blank=True, max_length=255)),
                ('linkC', models.CharField(blank=True, max_length=255)),
                ('linkD', models.CharField(blank=True, max_length=255)),
                ('linkE', models.CharField(blank=True, max_length=255)),
                ('linkF', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(choices=[('html', 'html'), ('css', 'css'), ('js', 'js'), ('dom', 'dom'), ('bootstrap', 'bootstrap'), ('python', 'python'), ('oop', 'oop'), ('django', 'django')], max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('publish', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, editable=False)),
            ],
        ),
    ]
