# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-03 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocontent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='code1',
        ),
        migrations.RemoveField(
            model_name='content',
            name='text1',
        ),
    ]
