# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-03 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocontent', '0002_auto_20200703_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='caption3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='content',
            name='caption4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='content',
            name='image3',
            field=models.ImageField(blank=True, default='default.png', upload_to='image/django/'),
        ),
        migrations.AddField(
            model_name='content',
            name='image4',
            field=models.ImageField(blank=True, default='default.png', upload_to='image/django/'),
        ),
    ]
