# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-03 15:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocontent', '0003_auto_20200703_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='caption5',
        ),
        migrations.RemoveField(
            model_name='content',
            name='code5',
        ),
        migrations.RemoveField(
            model_name='content',
            name='content5',
        ),
        migrations.RemoveField(
            model_name='content',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='content',
            name='text5',
        ),
        migrations.RemoveField(
            model_name='content',
            name='title5',
        ),
    ]
